version: "3.8"

services:

  chrome_browser:
    image: "selenium/standalone-chrome:latest"
    hostname: chrome
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"]
      interval: 15s
      timeout: 30s
      retries: 5
    depends_on:
      - db

  scraper:
    build: .
    depends_on:
      - chrome_browser
      - db
    entrypoint: ["./wait-for.sh", "chrome_browser:4444", "--", "python3", "program.py"]
    command: ["python3", "program.py"]

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - config.ini
    environment:
      MYSQL_DATABASE: '${REKYL_PORTAL_MYSQL_DB}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${REKYL_PORTAL_MYSQL_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${REKYL_PORTAL_MYSQL_PW}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${REKYL_PORTAL_MYSQL_ROOT_PW}'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
